apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo
        image: pankajkatyare/todo-list:latest
        ports:
        - containerPort: 8080
