// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.3
// source: internal/reminder/grpc/reminder.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RemainingTime string `protobuf:"bytes,4,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
	Status        string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateReminderRequest) Reset() {
	*x = CreateReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderRequest) ProtoMessage() {}

func (x *CreateReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderRequest.ProtoReflect.Descriptor instead.
func (*CreateReminderRequest) Descriptor() ([]byte, []int) {
	return file_internal_reminder_grpc_reminder_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateReminderRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateReminderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateReminderRequest) GetRemainingTime() string {
	if x != nil {
		return x.RemainingTime
	}
	return ""
}

func (x *CreateReminderRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result bool   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CreateReminderResponse) Reset() {
	*x = CreateReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReminderResponse) ProtoMessage() {}

func (x *CreateReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReminderResponse.ProtoReflect.Descriptor instead.
func (*CreateReminderResponse) Descriptor() ([]byte, []int) {
	return file_internal_reminder_grpc_reminder_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReminderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateReminderResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type GetReminderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RemainingTime string `protobuf:"bytes,2,opt,name=remaining_time,json=remainingTime,proto3" json:"remaining_time,omitempty"`
}

func (x *GetReminderRequest) Reset() {
	*x = GetReminderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderRequest) ProtoMessage() {}

func (x *GetReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderRequest.ProtoReflect.Descriptor instead.
func (*GetReminderRequest) Descriptor() ([]byte, []int) {
	return file_internal_reminder_grpc_reminder_proto_rawDescGZIP(), []int{2}
}

func (x *GetReminderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReminderRequest) GetRemainingTime() string {
	if x != nil {
		return x.RemainingTime
	}
	return ""
}

type GetReminderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result *CreateReminderRequest `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetReminderResponse) Reset() {
	*x = GetReminderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReminderResponse) ProtoMessage() {}

func (x *GetReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_reminder_grpc_reminder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReminderResponse.ProtoReflect.Descriptor instead.
func (*GetReminderResponse) Descriptor() ([]byte, []int) {
	return file_internal_reminder_grpc_reminder_proto_rawDescGZIP(), []int{3}
}

func (x *GetReminderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReminderResponse) GetResult() *CreateReminderRequest {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_reminder_grpc_reminder_proto protoreflect.FileDescriptor

var file_internal_reminder_grpc_reminder_proto_rawDesc = []byte{
	0x0a, 0x25, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x4b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x5d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2e,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x8f,
	0x01, 0x0a, 0x0c, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x43, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x18, 0x5a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x65, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_reminder_grpc_reminder_proto_rawDescOnce sync.Once
	file_internal_reminder_grpc_reminder_proto_rawDescData = file_internal_reminder_grpc_reminder_proto_rawDesc
)

func file_internal_reminder_grpc_reminder_proto_rawDescGZIP() []byte {
	file_internal_reminder_grpc_reminder_proto_rawDescOnce.Do(func() {
		file_internal_reminder_grpc_reminder_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_reminder_grpc_reminder_proto_rawDescData)
	})
	return file_internal_reminder_grpc_reminder_proto_rawDescData
}

var file_internal_reminder_grpc_reminder_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_reminder_grpc_reminder_proto_goTypes = []interface{}{
	(*CreateReminderRequest)(nil),  // 0: CreateReminderRequest
	(*CreateReminderResponse)(nil), // 1: CreateReminderResponse
	(*GetReminderRequest)(nil),     // 2: GetReminderRequest
	(*GetReminderResponse)(nil),    // 3: GetReminderResponse
}
var file_internal_reminder_grpc_reminder_proto_depIdxs = []int32{
	0, // 0: GetReminderResponse.result:type_name -> CreateReminderRequest
	0, // 1: TodoReminder.CreateReminder:input_type -> CreateReminderRequest
	2, // 2: TodoReminder.GetReminder:input_type -> GetReminderRequest
	1, // 3: TodoReminder.CreateReminder:output_type -> CreateReminderResponse
	3, // 4: TodoReminder.GetReminder:output_type -> GetReminderResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_reminder_grpc_reminder_proto_init() }
func file_internal_reminder_grpc_reminder_proto_init() {
	if File_internal_reminder_grpc_reminder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_reminder_grpc_reminder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_reminder_grpc_reminder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_reminder_grpc_reminder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_reminder_grpc_reminder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReminderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_reminder_grpc_reminder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_reminder_grpc_reminder_proto_goTypes,
		DependencyIndexes: file_internal_reminder_grpc_reminder_proto_depIdxs,
		MessageInfos:      file_internal_reminder_grpc_reminder_proto_msgTypes,
	}.Build()
	File_internal_reminder_grpc_reminder_proto = out.File
	file_internal_reminder_grpc_reminder_proto_rawDesc = nil
	file_internal_reminder_grpc_reminder_proto_goTypes = nil
	file_internal_reminder_grpc_reminder_proto_depIdxs = nil
}
